/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Burden' at '17/11/11 20:39' with Gradle 2.13
 *
 * @author Burden, @date 17/11/11 20:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
